version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "03:24"
    open-pull-requests-limit: 10
    target-branch: "develop"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "04:45"
    open-pull-requests-limit: 10
    target-branch: "develop"
